Add wireguard config

diff --git a/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway b/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
--- a/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
+++ b/src/packages/fff/fff-gateway/files/usr/sbin/configuregateway
@@ -28,8 +28,8 @@ BOARD="$(uci get board.model.name)"
 
 
 # ensure client config exists
-if ! uci -q get gateway.@client[0] > /dev/null; then
-    echo "ERROR: No client config!"
+if ! uci get gateway.@client[0] > /dev/null; then
+    echo "ERROR: No client config or error parsing config!"
     exit 1
 fi
 
@@ -288,13 +288,14 @@ remove_babelpeer() {
             uci del network.$name
             # remove babel interface
             uci del babeld.$name
+            # remove wireguard config
+            uci -q del network.@wireguard_$name[0]
         fi
     fi
 }
 
 config_load babeld
 config_foreach remove_babelpeer interface
-
 
 #add new peers
 add_babelpeer() {
@@ -360,5 +361,68 @@ add_babelpeer() {
 config_load gateway
 config_foreach add_babelpeer babelpeer
 
+
+
+## wireguardpeer
+#add new peers
+add_wgpeer() {
+    local name="$1"
+
+    # prohibit cfg* as name
+    if echo $name | grep cfg > /dev/null; then
+        echo "ERROR: name $name is invalid for wireguardpeer!"
+        return
+    fi
+
+    # add interface
+    uci set network.$name=interface
+    uci set network.$name.proto=wireguard
+    if uci -q get gateway.$name.private_key > /dev/null; then
+        uci set network.$name.private_key="$(uci get gateway.$name.private_key)"
+    else
+        privkey=$(wg genkey)
+        uci set network.$name.private_key="$privkey"
+        uci set gateway.$name.private_key="$privkey"
+    fi
+    echo "WIREGUARD: publickey for ${name}: $(echo $(uci get gateway.$name.private_key) | wg pubkey)"
+
+    # configure wireguard
+    cfg=$(uci add network wireguard_$name)
+    uci set network.$cfg.public_key="$(uci get gateway.$name.public_key)"
+    uci set network.$cfg.endpoint_host="$(uci get gateway.$name.endpoint_host)"
+    uci set network.$cfg.endpoint_port="$(uci get gateway.$name.endpoint_port)"
+    uci set network.$cfg.persistent_keepalive="$(uci get gateway.$name.persistent_keepalive)"
+    uci add_list network.$cfg.allowed_ips='::/0'
+    uci add_list network.$cfg.allowed_ips='0.0.0.0/0'
+
+    # remove old addresses
+    uci -q del network.$name.addresses
+
+    # link local
+    uci add_list network.$name.addresses="$(ipEUIAssemble "fe80::/64" "$SWITCHDEV")"
+
+    # peer_ip
+    if uci -q get gateway.@gateway[0].peer_ip; then
+        uci add_list network.$name.addresses="$(uci get gateway.@gateway[0].peer_ip)"
+    elif uci -q get gateway.@client[0].ipaddr; then
+        # use ipaddr (without subnet) if no peer_ip set
+        uci add_list network.$name.addresses="$(uci get gateway.@client[0].ipaddr | cut -d / -f1)"
+    else
+        echo "FATAL: Neither peer_ip nor ipaddr set! No peering ipv4 set!"
+    fi
+
+    # peer_ip6
+    if uci -q get gateway.@gateway[0].peer_ip6; then
+        uci add_list network.$name.addresses=$(uci get gateway.@gateway[0].peer_ip6)
+    fi
+
+    # add babel interface
+    uci set babeld.$name=interface
+    uci set babeld.$name.ifname="$name"
+    uci set babeld.$name.type='tunnel'
+}
+
+config_load gateway
+config_foreach add_wgpeer wireguardpeer
 
 exit 0
